Further steps for Lua 5.2 support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13,6 +13,7 @@ LUA_DIR="/usr"
 LUA_BINDIR="/usr/bin"
 LUA_INCDIR="/usr/include"
 LUA_LIBDIR="/usr/lib"
+LUA_VERSION="5.1"
 
 # ----------------------------------------------------------------------------
 # FUNCTION DEFINITIONS
@@ -37,6 +38,8 @@ system's package manager.
 --rocks-tree=FILE           Root of the local tree of installed rocks.
                             Default is \$PREFIX
 
+--lua-version=VERSION       Use specific Lua version: 5.1 or 5.2 (EXPERIMENTAL)
+                            Default is "$LUA_VERSION"
 --lua-suffix=SUFFIX         Versioning suffix to use in Lua filenames.
                             Default is "$LUA_SUFFIX" (lua$LUA_SUFFIX...)
 --with-lua=PREFIX           Use Lua from given prefix.
@@ -83,6 +86,14 @@ find_program() {
    fi
 }
 
+die() {
+   echo "$*"
+   echo
+   echo "configure failed."
+   echo
+   exit 1
+}
+
 find_helper() {
    explanation="$1"
    shift
@@ -99,8 +110,7 @@ find_helper() {
       shift
    done
    echo "Could not find a $explanation. Tried: $tried."
-   echo "Make sure one of them is installed and available in your PATH."
-   exit 1
+   die "Make sure one of them is installed and available in your PATH."
 }
 
 case `echo -n x` in
@@ -110,11 +120,6 @@ esac
 
 echo_n() {
    echo $echo_n_flag "$*"
-}
-
-die() {
-   echo "$*"
-   exit 1
 }
 
 # ----------------------------------------------------------------------------
@@ -162,6 +167,12 @@ do
       LUA_SUFFIX="$value"
       LUA_SUFFIX_SET=yes
       ;;
+   --lua-version)
+      [ -n "$value" ] || die "Missing value in flag $key."
+      LUA_VERSION="$value"
+      [ "$LUA_VERSION" = "5.1" -o "$LUA_VERSION" = "5.2" ] || die "Invalid Lua version in flag $key."
+      LUA_VERSION_SET=yes
+      ;;
    --with-lua)
       [ -n "$value" ] || die "Missing value in flag $key."
       LUA_DIR="$value"
@@ -181,7 +192,7 @@ do
       [ -n "$value" ] || die "Missing value in flag $key."
       case "$value" in
       wget|curl) LUAROCKS_DOWNLOADER="$value" ;;
-      *) echo "Invalid option: $value. See --help." ; exit 1 ;;
+      *) die "Invalid option: $value. See --help." ;;
       esac
       LUAROCKS_DOWNLOADER_SET=yes
       ;;
@@ -189,18 +200,16 @@ do
       [ -n "$value" ] || die "Missing value in flag $key."
       case "$value" in
       md5sum|openssl|md5) LUAROCKS_MD5CHECKER="$value" ;;
-      *) echo "Invalid option: $value. See --help." ; exit 1 ;;
+      *) die "Invalid option: $value. See --help." ;;
       esac
       LUAROCKS_MD5CHECKER_SET=yes
       ;;
    *)
-      echo "Error: Unknown flag: $1"
-      exit 1
+      die "Error: Unknown flag: $1"
       ;;
    esac
    shift
 done
-
 
 if [ "$PREFIX_SET" = "yes" -a ! "$SYSCONFDIR_SET" = "yes" ]
 then
@@ -216,26 +225,68 @@ then
    ROCKS_TREE=$PREFIX
 fi
 
+detect_lua_version() {
+   detected_lua=`$1 -e 'print(_VERSION:sub(5))' 2> /dev/null`
+   if [ "$detected_lua" = "5.1" -o "$detected_lua" = "5.2" ]
+   then
+      echo "Lua version detected: $detected_lua"
+      if [ "$LUA_VERSION_SET" != "yes" ]
+      then
+         LUA_VERSION=$detected_lua
+      elif [ "$LUA_VERSION" != "$detected_lua" ]
+      then
+         die "This clashes with the value of --with-lua-version. Please check your configuration."
+      fi
+   fi
+}
+
+search_interpreter() {
+   LUA_SUFFIX="$1"
+   if [ "$LUA_DIR_SET" = "yes" ]
+   then
+      if [ -f "$LUA_DIR/bin/lua$suffix" ]
+      then
+         find_lua="$LUA_DIR/bin"
+      fi
+   else
+      find_lua=`find_program lua$suffix`
+   fi
+   if [ -n "$find_lua" ]
+   then
+      echo "Lua interpreter found: $find_lua/lua$suffix..."
+      detect_lua_version "$find_lua/lua$suffix"
+      return 0
+   fi
+   return 1
+}
+
 if [ "$LUA_SUFFIX_SET" != "yes" ]
 then
-   for suffix in "" "5.1" "51" ""
+   if [ "$LUA_VERSION_SET" = "yes" -a "$LUA_VERSION" = "5.1" ]
+   then
+      suffixes="5.1 51"
+   elif [ "$LUA_VERSION_SET" = "yes" -a "$LUA_VERSION" = "5.2" ]
+   then
+      suffixes="5.2 52"
+   else
+      suffixes="5.2 52 5.1 51"
+   fi
+   for suffix in "" `echo $suffixes` ""
    do
-      LUA_SUFFIX="$suffix"
-      if [ "$LUA_DIR_SET" = "yes" ]
-      then
-         if [ -f "$LUA_DIR/bin/lua$suffix" ]
-         then
-            find_lua="$LUA_DIR"
-         fi
-      else
-         find_lua=`find_program lua$suffix`
-      fi
-      if [ -n "$find_lua" ]
-      then
-         echo "Lua interpreter found: $find_lua/lua$suffix..."
-         break
-      fi
+      search_interpreter "$suffix" && break
    done
+fi
+
+if [ "$LUA_VERSION" = "5.2" ]
+then
+   echo "******************************"
+   echo "WARNING: Lua 5.2 support is still experimental."
+   echo "Bug reports, patches and pull requests are welcome"
+   echo "at the GitHub project:"
+   echo "http://github.com/keplerproject/luarocks"
+   echo "and the mailing list:"
+   echo "https://lists.sourceforge.net/lists/listinfo/luarocks-developers"
+   echo "******************************"
 fi
 
 if [ "$LUA_DIR_SET" != "yes" ]
@@ -253,8 +304,7 @@ then
       echo "lua$LUA_SUFFIX found in \$PATH: $find_lua"
    else
       echo "lua$LUA_SUFFIX not found in \$PATH."
-      echo "You may want to use the flags --with-lua and/or --lua-suffix. See --help."
-      exit 1
+      die "You may want to use the flags --with-lua and/or --lua-suffix. See --help."
    fi
 fi
 
@@ -279,15 +329,14 @@ if [ -f "$lua_h" ]
 then
    echo "lua.h found in $lua_h"
 else
-   LUA_INCDIR="$LUA_INCDIR/lua5.1"
+   LUA_INCDIR="$LUA_INCDIR/lua/$LUA_VERSION"
    d_lua_h="$LUA_INCDIR/lua.h"
    if [ -f "$d_lua_h" ]
    then
       echo "lua.h found in $d_lua_h (Debian/Ubuntu)"
    else
       echo "lua.h not found (looked in $lua_h)"
-      echo "You may want to use the flag --with-lua-include. See --help."
-      exit 1
+      die "You may want to use the flag --with-lua-include. See --help."
    fi
 fi
 
@@ -308,16 +357,14 @@ if uname -s
 then
    LUAROCKS_UNAME_S=`uname -s`
 else
-   echo "Could not determine operating system. 'uname -s' failed."
-   exit 1
+   die "Could not determine operating system. 'uname -s' failed."
 fi
 echo_n "Configuring for architecture... "
 if uname -m
 then
    LUAROCKS_UNAME_M=`uname -m`
 else
-   echo "Could not determine processor architecture. 'uname -m' failed."
-   exit 1
+   die "Could not determine processor architecture. 'uname -m' failed."
 fi
 
 if [ -f config.unix ]; then
@@ -334,6 +381,7 @@ cat <<EOF > config.unix
 # This file was automatically generated by the configure script.
 # Run "./configure --help" for details.
 
+LUA_VERSION=$LUA_VERSION
 PREFIX=$PREFIX
 SYSCONFDIR=$SYSCONFDIR
 ROCKS_TREE=$ROCKS_TREE
